export const GET_INGREDIENTS_REQUEST:'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS:'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED:'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';
export const SET_CURRENT_INGREDIENT:'SET_CURRENT_INGREDIENT' = 'SET_CURRENT_INGREDIENT';
export const DELETE_CURRENT_INGREDIENT:'DELETE_CURRENT_INGREDIENT' = 'DELETE_CURRENT_INGREDIENT';
export const ADD_INGREDIENT_TO_CONSTRUCTOR:'ADD_INGREDIENT_TO_CONSTRUCTOR' = 'ADD_INGREDIENT_TO_CONSTRUCTOR';
export const DELETE_INGREDIENT_FROM_CONSTRUCTOR:'DELETE_INGREDIENT_FROM_CONSTRUCTOR' = 'DELETE_INGREDIENT_FROM_CONSTRUCTOR';
export const INCREASE_INGREDIENT_COUNTER:'INCREASE_INGREDIENT_COUNTER' = 'INCREASE_INGREDIENT_COUNTER';
export const GET_ORDER_NUMBER_REQUEST:'GET_ORDER_NUMBER_REQUEST' = 'GET_ORDER_NUMBER_REQUEST';
export const GET_ORDER_NUMBER_SUCCESS:'GET_ORDER_NUMBER_SUCCESS' = 'GET_ORDER_NUMBER_SUCCESS';
export const GET_ORDER_NUMBER_FAILED:'GET_ORDER_NUMBER_FAILED' = 'GET_ORDER_NUMBER_FAILED';
export const CLEAR_ORDER_NUMBER:'CLEAR_ORDER_NUMBER' = 'CLEAR_ORDER_NUMBER';
export const REPLACE_INGREDIENTS:'REPLACE_INGREDIENTS' = 'REPLACE_INGREDIENTS';

export const IS_REQUESTING:'IS_REQUESTING' = 'IS_REQUESTING';
export const IS_FAILED:'IS_FAILED' = 'IS_FAILED';
export const IS_SUCCESSFUL:'IS_SUCCESSFUL' = 'IS_SUCCESSFUL';

export const WS_CONNECTION_START:'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS:'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_CLOSED:'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_CONNECTION_ERROR:'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_GET_MESSAGE:'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';

export const WS_USER_CONNECTION_START:'WS_USER_CONNECTION_START' = 'WS_USER_CONNECTION_START';
export const WS_USER_CONNECTION_SUCCESS:'WS_USER_CONNECTION_SUCCESS' = 'WS_USER_CONNECTION_SUCCESS';
export const WS_USER_CONNECTION_CLOSED:'WS_USER_CONNECTION_CLOSED' = 'WS_USER_CONNECTION_CLOSED';
export const WS_USER_CONNECTION_ERROR:'WS_USER_CONNECTION_ERROR' = 'WS_USER_CONNECTION_ERROR';
export const WS_USER_GET_MESSAGE:'WS_USER_GET_MESSAGE' = 'WS_USER_GET_MESSAGE';